services:
#    app.example:
#        class:     AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#        calls:
#            - [setService, ["@service_id"]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
regra_manager:
	class: RegraManager
	arguments: [ @doctrine.orm.entity_manager ]

app.manager.facto_manager:
	class: AppBundle\Manager\FactoManager
	arguments: [ @doctrine.orm.entity_manager ]

app.manager.conector_manager:
	class: AppBundle\Manager\ConectorManager
<<<<<<< HEAD
	arguments: [ @doctrine.orm.entity_manager ]

app.model.base_conocimiento_model:
	class: AppBundle\Model\BaseConocimientoModel
=======
>>>>>>> f888585958ac5d79ea1e0c1eb7c7b46434325de6
	arguments: [ @doctrine.orm.entity_manager ]