<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Base_ConocimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Base_ConocimientoRepository extends EntityRepository
{
}
