<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactoRepository extends EntityRepository
{
   public function PegarFactoRegra($id_facto){
       return $this->_em->getRepository('AppBundle:Facto')->find($id_facto);
   }
}
