<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Regra_producaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Regra_producaoRepository extends EntityRepository
{
}
